name: Ai Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ai_pr_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: sum20156/QuickDev-AI-Pr-Reveiwer@master
        with:
          standards: "Check memory leaks, function lines should not exceed 15" #list of code quality standards you follow
          target_extensions: "kt,xml" #only for these extensions code quality will be checked
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }} #Currently it uses gemini Ai
          github_token:  ${{ secrets.GITHUB_TOKEN }}
